all:
  hosts:
    master:
      ansible_host: 192.168.56.10
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/master/virtualbox/private_key
    node01:
      ansible_host: 192.168.56.11
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/node01/virtualbox/private_key
    node02:
      ansible_host: 192.168.56.12
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/node02/virtualbox/private_key
    node03:
      ansible_host: 192.168.56.13
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/node03/virtualbox/private_key
  children:
    workers:
      hosts:
        node01:
        node02:
        node03:
  vars:
    docker_swarm_manager_ip: 192.168.56.10  # Variável reutilizável nos playbooks
