---
- name: Configurar Docker Swarm
  host: all
  become: true
  tasks:

    - name: Inicia Docker Swarm no Manager
      command: docker swarm init --advertise-addr 192.168.56.10
      args:
        creates: /var/lib/docker/swarm
      register: swarm-init
      when: inventory_hostname == 'master'

    - name: Token de worker
      command: docker swarm join-token worker -q
      register: worker_token
      when: inventory_hostname == 'master'

    - name: Copia o token para os workers
      set_fact:
        swarm_worker_token: "{{ hostvars['master'].worker_token.stdout }}"
      when: inventory_hostname in groups['workers'] and worker_token is defined

    - name: Juntar workers ao Swarm
      command: docker swarm join --token {{ swarm_worker_token }} 192.168.56.10:2377
      args:
        creates: /var/lib/docker/swarm
      when: inventory_hostname in groups['workers'] and swarm_worker_token is defined