---
- hosts: all
  become: true
  tasks:
    - name: Iniciar e habilitar o serviço firewalld
      systemd:
        name: firewalld
        state: started
        enabled: yes
    - name: Liberar as portas do Swarm
      firewalld:
        port: "{{item}}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - 2377/tcp
        - 7946/tcp
        - 7946/udp
        - 4789/udp
