---
- hosts: all
  become: true
  tasks:

    - name: Atualizar o sistema
      dnf:
        name: '*'
        state: latest
        update_cache: yes

    - name: Instala dnf-plugins-core
      dnf:
        name: dnf-plugins-core
        state: present

    - name: Baixar script de instalação do Docker
      get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: '0755'

    - name: Executar script de instalação do Docker
      command: /tmp/get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: Ativa e inicia o serviço do Docker
      systemd:
        name: docker
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Adicionar usuário vagrant ao grupo docker
      user:
        name: vagrant
        groups: docker
        append: yes